---
- name: Desplegar Games API
  hosts: webservers
  become: yes  # Ejecutar como administrador (sudo)

  tasks:
    # 1. Asegurar que Docker y Python estén instalados (requisitos)
    - name: Instalar pip3 (necesario para el módulo docker de ansible)
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Instalar Docker SDK para Python
      pip:
        name: docker

    # 2. Transferir el archivo docker-compose (Requisito Fase 2.4.c.i)
    - name: Copiar docker-compose.yml al servidor
      copy:
        src: ./docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        mode: '0644'

    # 3. Descargar la última versión de tu imagen (Requisito Fase 2.4.c.ii)
    - name: Hacer pull de la imagen más reciente
      command: docker-compose pull
      args:
        chdir: /home/{{ ansible_user }}/

    # 4. Levantar los contenedores (Requisito Fase 2.4.c.iii)
    - name: Levantar servicios con Docker Compose
      docker_compose:
        project_src: /home/{{ ansible_user }}/
        state: present
        recreated: always # Fuerza a recrear si la imagen cambió